spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:reconnect}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:reconnect}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

app:
  storage:
    type: relational
  jwt:
    secret: ${JWT_SECRET:changeThisInProductionToASecureRandomString12345678901234567890}
    expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
