spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  storage:
    type: file
    location: data/

filedb:
  contacts-file: contacts.txt
  groups-file: groups.txt
  interactions-file: interactions.txt
